### PR TITLE
update readme urls and docker file go 1.81 -> 1.21

### PR DESCRIPTION
**Pull request by tjex**
As stated in title. 

In preparation for zk release 0.14.1

### CODE REVIEW

**Comment by tjex** [comment]
hmm. I see a problem here, that this would require a zk-org account on docker hub. Closing for now.

**Comment by mcDevnagh** [comment]
why don't we make a zk-org account?

**Comment by tjex** [comment]
Since writing this, I'm unsure if a shared account makes so much sense.

1. We can build locally from the images in this repo
2. I think it's worth looking at transitioning away from mattn's sqlite library, so we don't need to cross compile with Docker in the first place.

That being said, if you and or others still consider a shared account to be the best way, then I'm down. It would be great then if someone could then make it.

Not sure how to share the password. Maybe someone has 1password and can share an encrypted one time sharing of the password that we can insert into our own managers.

**Comment by julio-lopez** [comment]
Why not push to Github (ghcr) instead of Docker (Hub) ? That is simpler and does not require creating a separate account / org with Docker and maintaining credentials, etc.

**Comment by tjex** [comment]
Ah awesome. Didn't know this was a thing.

Sounds like the best solution. I'll set this up once the `musl` images are done zk-org/zk#411 

And will then update / close #4, whichever makes most sense given the `ghcr` setup.

**Pull request closed without merging**
